from __future__ import annotations

import secrets
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse


@dataclass(frozen=True)
class EnvField:
    key: str
    comment: str
    required: bool = False
    default: str | None = None
    derived_from: str | None = None


REGISTRY: tuple[EnvField, ...] = (
    EnvField("RP_ORIGIN", "Canonical external origin, must include scheme.", True),
    EnvField("RP_NAME", "Display name shown to authenticators.", True),
    EnvField(
        "RP_ID",
        "Derived from RP_ORIGIN hostname. Keep aligned with RP_ORIGIN.",
        True,
        derived_from="RP_ORIGIN",
    ),
    EnvField("SECRET_KEY", "Flask session/signing secret key.", True),
    EnvField("SECURITY_PASSWORD_SALT", "Password hashing/recovery salt.", True),
    EnvField(
        "DATABASE_PATH",
        "SQLite database location.",
        default="resources/app.sqlite3",
    ),
    EnvField("LOG_DIR", "Application log directory.", default="logs"),
    EnvField("LOG_FILENAME", "Application log filename.", default="app.log"),
    EnvField("LOG_LEVEL", "Python log level.", default="INFO"),
    EnvField(
        "LOG_MAX_KB",
        "Rotate logs when this size in KB is exceeded.",
        default="1024",
    ),
)


def derive_rp_id(rp_origin: str) -> str:
    parsed = urlparse(rp_origin)
    if not parsed.hostname:
        msg = "Cannot derive RP_ID: RP_ORIGIN is missing a hostname."
        raise ValueError(msg)
    return parsed.hostname


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def generated_defaults(existing: dict[str, str]) -> dict[str, str]:
    defaults: dict[str, str] = {}
    if "SECRET_KEY" not in existing:
        defaults["SECRET_KEY"] = secrets.token_urlsafe(48)
    if "SECURITY_PASSWORD_SALT" not in existing:
        defaults["SECURITY_PASSWORD_SALT"] = secrets.token_urlsafe(32)
    return defaults


def merged_env(existing: dict[str, str], supplied: dict[str, str]) -> dict[str, str]:
    merged = dict(existing)
    merged.update({k: v for k, v in supplied.items() if v})
    merged.update(generated_defaults(merged))

    if "RP_ORIGIN" in merged and merged["RP_ORIGIN"]:
        merged["RP_ID"] = derive_rp_id(merged["RP_ORIGIN"])

    for field in REGISTRY:
        if field.key not in merged and field.default is not None:
            merged[field.key] = field.default

    return merged


def render_env_file(values: dict[str, str]) -> str:
    lines: list[str] = [
        "# Generated by: flask init-env",
        "# Update values as needed. Existing values are preserved on re-run.",
        "",
    ]
    for field in REGISTRY:
        lines.append(f"# {field.comment}")
        if field.derived_from:
            lines.append(f"# Derived from: {field.derived_from}")
        value = values.get(field.key, "")
        lines.append(f"{field.key}={value}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
