[project]
name = "webauthn-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kristian Koehntopp", email = "kris-git@koehntopp.de" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.0",
    "flask-mail>=0.10.0",
    "flask-migrate>=4.1.0",
    "flask-security-too>=5.6.0",
    "flask-sqlalchemy>=3.1.1",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.38",
    "webauthn>=2.7.0",
]

[project.scripts]
webauthn-test = "webauthn_test:main"

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
include = ["src/**/*.py", "tests/**/*.py"]
src = ["src", "tests"]

[tool.mypy]
files = ["src"]
ignore_missing_imports = true

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.4",
    "ruff>=0.9.6",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
