[project]
name = "webauthn-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kristian Koehntopp", email = "kris-git@koehntopp.de" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
webauthn-test = "webauthn_test:main"

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
include = ["src/**/*.py", "tests/**/*.py"]
src = ["src", "tests"]

[tool.mypy]
files = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
